dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "kitswdevteam-github"
    branches:
      - master
      - module-1
      - module-2
      - module-3

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'